import type { Metadata } from "next";
import styles from './layout.module.css';
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.body}`}>
        <main className={styles.main}>
          <div className={styles.div}>{children}</div>
        </main>
      </body>
    </html>
  );
}
